### ISSUE TITLE
Horizontal scroll bar in dribbble.html

### ISSUE THREAD

**Issue by gauthamcode** [gauthamcode/Personal-Website#4]
The positioning is messed up in this html. I want the picture of the cow to be aligned to the bottom-center of the page, I've tried doing so using flexbox. The result that I'm getting using my code is very dodgy. Have to fix this issue ASAP.

Note: Page has to be responsive.

**Comment by gauthamcode** [comment]
@libhide The cow isn't bottom aligned on my screen. On smaller screens this issue isn't seen but try using the chrome dev tools to mimic a larger screen ("Laptop with HiDPI" or something similar). There's a space below the cow, which makes it look a bit awkard.

**Comment by libhide** [comment]
Like I said in the message for my pull request, that is bound to happen unless you switch over to absolute positioning.
